### PR TITLE
Refactoring of repeated tasks and more general processing

### PR DESCRIPTION
**Pull request by daliboris**
- indentation switched to on; 
- refactoring (repeated attributes as the template), 
- ocrx_block element (hOCR from <https://www.digitale-sammlungen.de/>), 
- @ID attribute generated if not in the source
- better identification of bbox value for whole page (if there are multiple properties in the @title property); 
- adding page number if it is in the source

TODO: better processing of all hOCR properties

### CODE REVIEW

**Review by filak — CHANGES_REQUESTED** [review]
Thank you for the request. Your proposals will be valuable additions.

Would you be so kind and fix the typos (though there is no impact on the functionality): 

- variable name "properites" => properties
- template name "add-posioton-attributes" => add-position-attributes

Also it would be nice to update the other hocr to alto stylesheets as well:

https://github.com/filak/hOCR-to-ALTO/blob/master/hocr__alto2.0.xsl
https://github.com/filak/hOCR-to-ALTO/blob/master/hocr__alto2.1.xsl
https://github.com/filak/hOCR-to-ALTO/blob/master/hocr__alto3.xsl

**Comment by filak** [comment]
@daliboris Are you still interested in this PR ?

**Comment by daliboris** [comment]
I'm sorry, @filak, I had forgotten about this problem. I'll come back to it next week.

**Comment by daliboris** [comment]
@filak what is the purpose of the `$teslang` parameter and attribute `@teslang`? They are used in the `<xsl:choose>` function to set the `@language` or `@LANG` value in the ALTO (see [this code](https://github.com/filak/hOCR-to-ALTO/blob/3f597fa49f7a22a25b5b918d9e9d50314836b5e4/hocr__alto2.0.xsl#L111-L140), for example). But I can't  fing definition of the `@teslang` in hOcr specification. Am I missing something?

**Comment by filak** [comment]
I do not remember the use case(s) but these are just optional params:
```
  <!-- Optional params:
       - default language code (param:  language) OR
       - Tesseract language code (param:  teslang)
  -->
```

You can pass a Tesseract language code and get a proper 2-letter language code retrieved from this lookup file https://github.com/filak/hOCR-to-ALTO/blob/master/codes_lookup.xml

**Comment by daliboris** [comment]
> I do not remember the use case(s) but these are just optional params:
> 
> ```
>   
> ```
> 
> You can pass a Tesseract language code and get a proper 2-letter language code retrieved from this lookup file https://github.com/filak/hOCR-to-ALTO/blob/master/codes_lookup.xml

That was my first thought, but the code behaves differently:

```xml
<xsl:when test="$teslang != 'notset'">
   <xsl:variable name="lookup" select="@teslang" />
   <xsl:attribute name="LANG">
     <xsl:value-of select="$langcodes[@a3h=$lookup]/@a2" />
 </xsl:attribute>
```

If the `$teslang` parameter is set, then the value of the `@teslang` attribute (**not the parameter**) is searched for in the lookup file. Since the `@teslang` attribute is not part of the hOCR standard, I assume that `$teslang`  should be searched, i.e. using `<xsl:variable name="lookup" select="$teslang" />`.

**Comment by daliboris** [comment]
Hello @filak, I'm working on refactored version with minimal repeating code.

First draft is available here: <https://github.com/daliboris/hOCR-to-ALTO/tree/hocr-to-alto-refactoring>.

Code is divided into main XSLT stylesheet <https://github.com/daliboris/hOCR-to-ALTO/blob/hocr-to-alto-refactoring/hocr__alto.xsl> and partial stylesheets for each supported version of ALTO, for example <https://github.com/daliboris/hOCR-to-ALTO/blob/hocr-to-alto-refactoring/hocr__alto4.0.xsl>, to be compatible with previous versions of this set of stylesheets.

Is this approach OK for you?

**Comment by filak** [comment]
OK, I like the approach. I am looking forward testing this.

**Comment by filak** [comment]
Just please let me know when your branch is ready.

**Comment by daliboris** [comment]
Hello @filak, I'm done. 

I had to use a more general approach because of the namespaces of the transformed elements.

To create specific namespaces for different versions of ALTO I use `<xsl:element name="Description" namespace="{$namespace}">` instead of `<Description>`.

**Comment by filak** [comment]
Thank you, it looks great. I am going to do some testing ASAP.

**Review by filak — APPROVED** [review]

**Pull request merged**
